### ISSUE TITLE
Invalid module name in the prod terraform

### ISSUE THREAD

**Issue by kevinbrill** [turnerlabs/udeploy#10]
Attempting to terraform the prod instance of the portal results in the following error:

```
Error: Reference to undeclared module

  on infrastructure/portals/prod/main.tf line 61, in output "s3_change_queue":
  61:   value = module.dev.s3_change_queue
```

`module.dev.s3_change_queue` should be `module.env.s3_change_queue`

**Comment by kendavis2** [comment]
Issue appears to be resolved with the PR.
